# Run `goreleaser release --snapshot --rm-dist` for local testing
builds:
- id: "okrad"
  main: ./cmd/okrad
  binary: "okrad"
  dir: ./
  env: [CGO_ENABLED=0]
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
- id: "okra"
  main: ./cmd/okra
  binary: "okra"
  dir: ./
  env: [CGO_ENABLED=0]
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
- id: "aws"
  main: ./cmd/aws
  binary: "aws"
  dir: ./
  env: [CGO_ENABLED=0]
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
- id: "okractl"
  main: ./cmd/okractl
  binary: "okractl"
  dir: ./
  env: [CGO_ENABLED=0]
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
dockers:
- image_templates: ["ghcr.io/mumoshu/okra/{{ .ProjectName }}-amd64:{{ .Version }}"]
  dockerfile: Dockerfile.goreleaser
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/mumoshu/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/mumoshu/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
- image_templates: ["ghcr.io/mumoshu/okra/{{ .ProjectName }}-arm64v8:{{ .Version }}"]
  goarch: arm64
  dockerfile: Dockerfile.goreleaser
  use: buildx
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/mumoshu/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/mumoshu/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
- name_template: ghcr.io/mumoshu/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - ghcr.io/mumoshu/okra/{{ .ProjectName }}-amd64:{{ .Version }}
  - ghcr.io/mumoshu/okra/{{ .ProjectName }}-arm64v8:{{ .Version }}
- name_template: ghcr.io/mumoshu/{{ .ProjectName }}:latest
  image_templates:
  - ghcr.io/mumoshu/okra/{{ .ProjectName }}-amd64:{{ .Version }}
  - ghcr.io/mumoshu/okra/{{ .ProjectName }}-arm64v8:{{ .Version }}
