apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ include "okra.managerRoleName" . }}
rules:
- apiGroups:
  - okra.mumo.co
  resources:
  - awsapplicationloadbalancerconfigs
  - awstargetgroups
  - awstargetgroupsets
  - cells
  - clustersets
  - pauses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - okra.mumo.co
  resources:
  - awsapplicationloadbalancerconfigs/finalizers
  - awstargetgroups/finalizers
  - awstargetgroupsets/finalizers
  - cells/finalizers
  - clustersets/finalizers
  - pauses/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - okra.mumo.co
  resources:
  - awsapplicationloadbalancerconfigs/status
  - awstargetgroups/status
  - awstargetgroupsets/status
  - cells/status
  - clustersets/status
  - pauses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - analysisruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - analysisruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - okra.mumo.co
  resources:
  - pauses
  verbs:
  - deletecollection
- apiGroups:
  - argoproj.io
  resources:
  - analysisruns
  verbs:
  - deletecollection
