# permissions to do viewer clustersets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "okra.viewerRoleName" . }}
rules:
- apiGroups:
  - okra.mumo.co
  resources:
  - awsapplicationloadbalancerconfigs
  - awstargetgroups
  - awstargetgroupsets
  - cells
  - clustersets
  - pauses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - okra.mumo.co
  resources:
  - awsapplicationloadbalancerconfigs/status
  - awstargetgroups/status
  - awstargetgroupsets/status
  - cells/status
  - clustersets/status
  - pauses/status
  verbs:
  - get
